#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
redshift -P -O 5000 &
# polybar dracula &
setxkbmap gb &
setxkbmap -option ctrl:swapcaps &

bspc monitor HDMI-0 -d I II III IV V 
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focused_border_color \#642E78 
# bspc config normal_border_color  \#FF0000
# bspc config presel_feedback_color \#191A1E

xsetroot -cursor_name left_ptr &


# enable mouse for floating windows
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# rules for applications
#bspc rule -a Gimp desktop=^8 follow=on state=floating
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


bspc rule -a emacs state=fullscreen
